### PR TITLE
README create_image_collection example

### PR DESCRIPTION
**Pull request by ktoddbrown**
Thanks for what looks like it will be a very useful package! I think I found a small bug in the README example.

create_image_collection example needs to be inside the unziped folder otherwise L8.col comes up empty

### CODE REVIEW

**Comment by appelmar** [comment]
Thanks! Have you tried to render `README.Rmd`? The normal `README.md` as displayed on GitHub is generated from the R Markdown file and is typically not updated by hand.

**Comment by ktoddbrown** [comment]
Excellent point that I missed! The same comments should apply since the Rmd is located in the parent directory here. If you agree then I can go and edit that document as well and add that to the PR.

**Comment by appelmar** [comment]
That is interesting, because I do not really see how it can make a difference where the image collection file is stored. It should even work if we ignore the `out_file` argument. Could you please provide some more details? Thanks again!

**Comment by ktoddbrown** [comment]
Ok I'm not quite sure what was going on here but I'm not able to reproduce the error now. Which makes me think that one of the install support libraries hadn't quite been incorporated. I notice that I didn't have the library `stars` installed when I opened up the rmd file (probably not relevant). Closing this pull request and thank you for the consideration.

**Comment by appelmar** [comment]
Let me know if the issue pops up again!

**Pull request closed without merging**
